import { Injectable } from '@angular/core';

@Injectable()
export class TableDataService {
  tableData =[{
    id: 1,
    first_name: 'Douglass',
    last_name: 'Stickins',
    email: 'dstickins0@archive.org',
    gender: 'Male'
  }, {
    id: 2,
    first_name: 'Neille',
    last_name: 'Hardeman',
    email: 'nhardeman1@nhs.uk',
    gender: 'Female'
  }, {
    id: 3,
    first_name: 'Myron',
    last_name: 'Stambide',
    email: 'mstambide2@bluehost.com',
    gender: 'Male'
  }, {
    id: 4,
    first_name: 'Zeb',
    last_name: 'Devennie',
    email: 'zdevennie3@webs.com',
    gender: 'Male'
  }, {
    id: 5,
    first_name: 'Idnnie',
    last_name: 'Balthasar',
    email: 'sbalthasar4@odnoklassniki.ru',
    gender: 'Female'
  }, {
    id: 6,
    first_name: 'Erminie',
    last_name: 'McCluskey',
    email: 'emccluskey5@cocolog-nifty.com',
    gender: 'Female'
  }, {
    id: 7,
    first_name: 'Upton',
    last_name: 'Luigi',
    email: 'uluigi6@freewebs.com',
    gender: 'Male'
  }, {
    id: 8,
    first_name: 'Pieter',
    last_name: 'Blucher',
    email: 'pblucher7@bigcartel.com',
    gender: 'Male'
  }, {
    id: 9,
    first_name: 'Sibyl',
    last_name: 'Priestman',
    email: 'spriestman8@bloglovin.com',
    gender: 'Female'
  }, {
    id: 10,
    first_name: 'Millard',
    last_name: 'Bamford',
    email: 'mbamford9@acquirethisname.com',
    gender: 'Male'
  }, {
    id: 11,
    first_name: 'Chaddy',
    last_name: 'Starmore',
    email: 'cstarmorea@noaa.gov',
    gender: 'Male'
  }, {
    id: 12,
    first_name: 'Louie',
    last_name: 'Ville',
    email: 'lvilleb@ted.com',
    gender: 'Male'
  }, {
    id: 13,
    first_name: 'Allie',
    last_name: 'Scandroot',
    email: 'ascandrootc@nifty.com',
    gender: 'Female'
  }, {
    id: 14,
    first_name: 'Dougy',
    last_name: 'Rackstraw',
    email: 'drackstrawd@army.mil',
    gender: 'Male'
  }, {
    id: 15,
    first_name: 'Katti',
    last_name: 'McDonough',
    email: 'kmcdonoughe@deviantart.com',
    gender: 'Female'
  }, {
    id: 16,
    first_name: 'Micaela',
    last_name: 'Dilgarno',
    email: 'mdilgarnof@si.edu',
    gender: 'Female'
  }, {
    id: 17,
    first_name: 'Titus',
    last_name: 'Talkington',
    email: 'ttalkingtong@networksolutions.com',
    gender: 'Male'
  }, {
    id: 18,
    first_name: 'Rafaellle',
    last_name: 'Fylan',
    email: 'rfylanh@prweb.com',
    gender: 'Male'
  }, {
    id: 19,
    first_name: 'Rossie',
    last_name: 'Earengey',
    email: 'rearengeyi@wikipedia.org',
    gender: 'Male'
  }, {
    id: 20,
    first_name: 'Brigg',
    last_name: 'Langshaw',
    email: 'blangshawj@quantcast.com',
    gender: 'Male'
  }];
  constructor() { }

}
